INSERT INTO Category (description) VALUES ('American');
INSERT INTO Category (description) VALUES ('Italian');
INSERT INTO Category (description) VALUES ('Mexican');
INSERT INTO Category (description) VALUES ('Fast Food');
INSERT INTO unit_of_mesure (description) VALUES ('Teaspoon');
INSERT INTO unit_of_mesure (description) VALUES ('Tablespoon');
INSERT INTO unit_of_mesure (description) VALUES ('Cup');
INSERT INTO unit_of_mesure (description) VALUES ('Pinch');
INSERT INTO unit_of_mesure (description) VALUES ('Ounce');
INSERT INTO unit_of_mesure (description) VALUES ('Each');
INSERT INTO unit_of_mesure (description) VALUES ('Dash');
INSERT INTO unit_of_mesure (description) VALUES ('Pint');